gem 'rails',                    '3.0.0.beta2'
gem 'matthuhiggins-foreigner',  '0.5.0',      :require => 'foreigner'
gem 'sqlite3-ruby',             '1.2.5',      :require => 'sqlite3'
gem 'mysql',                    '2.8.1'
#gem 'factory_girl',             '1.2.4'